---
title: "greatsword users' right concern group member"
date: 2021-04-29
---
title: greatsword users' right concern group member
date: 2021-04-29
---
ok?
ok
date: 2021-04-29
author: capcom
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# social links
greatsword is nerfed too much, please buff.
what do you want
Google search results) and in your feed.xml site description.
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
---
