title: mhrise
author: me
email: pang771149@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 mhr greatsword needs a buff
 needs a buff
 abuff.com
# social links
twitter_username: pa3721ng # DO NOT include the @ character, or else the build will fail!
github_username:  pang3721 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
